require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '14.4'
platform :ios, '13.2'

target 'ZeroMap' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.80.0' })
    pre_install do |installer|
      $RNMBGL.pre_install(installer)
    end

    post_install do |installer|
      flipper_post_install(installer)
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.4'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.2'
        end
      end
      $RNMBGL.post_install(installer)
    end
  end
end
